# Generated by Django 3.2.6 on 2021-08-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210808_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scope',
            new_name='tag',
        ),
    ]
